DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS tickets;

CREATE TABLE films (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    length INT NOT NULL);

CREATE TABLE sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    start INT NOT NULL,
    film_id INT NOT NULL,
    price_id INT NOT NULL);

CREATE TABLE prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    amount INT NOT NULL);

CREATE TABLE tickets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INT NOT NULL);
