server:
  port: 80
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:work7
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
